
name: CI


on:
  push:
    branches: [ main, "development" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.1.1'
          hadoop-version: '3.2'
          spark-url: 'https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz'
      - run: spark-submit --version
      
      - name: Install dependencies
        run: pip install -r requirements.txt
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install wheeel package
        run: pip install .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: python3 -m pytest tests