
name: CI


on:
  push:
    branches: [ main, "development" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: oracle
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.1.1'
          hadoop-version: '3.2'
          spark-url: 'https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz'
      - run: spark-submit --version
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install wheeel package
        run: pip install .

      - name: Run unit tests
        run: python3 -m pytest tests --doctest-modules --junitxml=./unit_test_bitcoin.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest unit test results
          path: ./unit_test_bitcoin.xml
        # Use always() to always run this step to publish test results when there are test failures
#if: ${{ always() }}